### PR TITLE
Added fix for argument validation by cucumberjs and now returns promi…

### PR DESCRIPTION
**Pull request by markwylde**
Recently the guys at Cucumber have put a validation into the callback functions to make sure it has the same amount of arguments as the regex/pattern has requested.

Because we are using `co` and `apply`ing the arguments, the length of the Function object is 0. This now makes any step definition with arguments fail.

I have put in a workaround by using `Object.defineProperty` to set the length of the function to the same as the arguments given in the callback function.

I also had some trouble with artstep giving false positives because it wasn't returning the generator function back up to cucumber. I added in a return statement before the co result to ensure the step definition doesn't finish until the co/promise is resolved.

### CODE REVIEW

**Comment by dtinth** [comment]
Thank you! Glad to hear that someone still uses this. Haven’t used Cucumber for quite some time. Please let me check with my existing project to see if all goes well.

**Comment by dtinth** [comment]
It worked! Thanks again for your patch! :smile:

**Comment by dtinth** [comment]
Some questions before I can release this:
- Why is `getParamNames` required? Shouldn’t it be possible just to use `fn.length` to find the length of function?

Also, the reason that it gives you false positives is because the returned function’s length is not added by 1, which tells Cucumber that it’s either a synchronous test or returns a promise. Therefore, it doesn’t give the callback.

**Comment by dtinth** [comment]
I just released v55555.0.0 that supports Cucumber 0.9. I did not use `getParamNames` but simply used `fn.length`. I tested with my code that uses Cucumber and it seems to work fine.

**Comment by markwylde** [comment]
Awesome @dtinth. `fn.length` is a much nicer solution, I should have thought of that!

> Glad to hear that someone still uses this

I hope your library will gain some more use when async functions and generators become more mainstream. It's an awesome library @dtinth. Thanks for all your work on it!

**Comment by dtinth** [comment]
Thank you for your kind compliments!

I made this library as a stopgap to make writing step definitions in Cucumber 0.4 more bearable. It seems that a lot has changed. Cucumber now supports promises (and by definition, async functions) out of the box! :smile:

**Pull request merged**
